dist: xenial
language: go
sudo: false
install:
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - go mod download
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals -D gosec --deadline 5m ./...
  - go test -race ./...
go:
  - 1.x
  - tip
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
