dist: xenial
language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
install:
  - export GOCACHE=$GOPATH/pkg/cache
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - go mod download
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals -D gosec --deadline 5m ./...
  - go test -race ./...
go:
  - 1.x
env:
  - GO111MODULE=on
matrix:
  fast_finish: true
