name: Go
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go_version: [1.11.13, 1.12.8, 1.13beta1]

    name: Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        id: go
        with:
          version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - name: go-mod-download
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: run-linter
        uses: docker://golangci/golangci-lint
        env:
          GOROOT: /usr/local/go
        with:
          entrypoint: golangci-lint
          args: run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m ./...

      - name: run-tests
        run: go test -mod readonly -race ./...
