name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "21 2 * * 2"
jobs:
  tests:
    strategy:
      matrix:
        go_version:
          - 1.14
          - 1.15
        os:
          - macos
          - ubuntu
          - windows

    name: tests (${{ matrix.os }}/go-${{ matrix.go_version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-go@v2.1.2
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v2.3.3

      - name: run-tests
        run: go test -mod readonly -race ./...

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: golangci/golangci-lint-action@v2.2.0
