name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "21 2 * * 2"
jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.13
          - 1.14
        os:
          - macos
          - ubuntu
          - windows

    name: Build (${{ matrix.os }}/go-${{ matrix.go_version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-go@master
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - name: install deps
        run: go mod download

      - name: run-tests
        run: go test -mod readonly -race ./...
        env:
          GOPROXY: off

      - name: install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        working-directory: /
        env:
          GO111MODULE: on

      - name: run-linter
        run: golangci-lint run
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly
